// List of valid medical specialties
List<String> medicalSpecialties = [
  'Allergy and Immunology',
  'Anesthesiology',
  'Audiology',
  'Cardiology',
  'Critical Care Medicine',
  'Clinical Genetics',
  'Dermatology',
  'Dentistry',
  'Diagnostic Radiology',
  'Emergency Medicine',
  'Endocrinology',
  'Family Medicine',
  'General medicine specialty',
  'Gastroenterology',
  'Geriatrics',
  'Gynecology',
  'Hematology',
  'Hospice and Palliative Medicine',
  'Infectious Disease',
  'Internal Medicine',
  'Medical Oncology',
  'Microbiology',
  'Nephrology',
  'Neurology',
  'Nuclear Medicine',
  'Obstetrics and Gynecology (OB-GYN)',
  'Occupational Medicine',
  'Ophthalmology',
  'Orthopedics',
  'Otolaryngology (ENT)',
  'Pathology',
  'Pediatrics',
  'Physical Medicine and Rehabilitation',
  'Plastic Surgery',
  'Preventive Medicine',
  'Psychiatry',
  'Pulmonology',
  'Radiology',
  'Rheumatology',
  'Surgery',
  'Sports Medicine',
  'Thoracic Surgery',
  'Toxicology',
  'Urology',
  'Vascular Medicine',
];
